workflows:
  ios-development:
    name: iOS Development Build
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build React app
        script: npm run build
      - name: Prepare Capacitor iOS project
        script: |
          npx cap init myapp com.myapp
          npx cap add ios
          npx cap sync ios
    artifacts:
      - ios/ipa/*.ipa
