workflows:
  ios-development:
    name: iOS Development Build
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Build React app
        script: npm run build
      - name: Prepare Capacitor iOS project
        script: |
          npx cap sync ios
